### ISSUE TITLE
Additional config for app_service_config_files not used

### ISSUE THREAD

**Issue by Karlinde** [cheasles/puppet-synapse#1]
When adding a file path to `app_service_config_files` via `synapse::additional_config` in a hiera yaml file, the value doesn't seem to be used by synapse. The expected behaviour is that the contents of additional_config would overwrite or merge with the existing values set in the homeserver.yaml template, but it looks like it's the other way around and the template contents take precedent.

When I remove the following line from `homeserver.yaml.erb`, the new value from additional_config starts to be used by synapse:
```
app_service_config_files: []
```

Possible solution might be to just remove this line from the template. Another solution might be to put the additional_config after the contents of the template when assembling homeserver.yaml. Is there any particular reason why it has been placed before the template?

**Comment by cheasles** [comment]
Hey @Karlinde thanks for reporting this.

The ordering was a quick hack to resolve an issue where `to_yaml` outputs a `---` line which tripped up synapse. Putting that at the top of the generated file resolved the issue.

I've removed the line from `homeserver.yaml.erb` like you suggest and everything seems to be working as usual so I'll push up the fix.

Thanks!

**Comment by cheasles** [comment]
Should be fixed in v1.0.1.
